"""initial

Revision ID: 53777753d994
Revises:
Create Date: 2026-01-29 20:54:08.998554

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "53777753d994"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
