"""fix subscr columns

Revision ID: f5023c388e33
Revises: 0c83425451a8
Create Date: 2026-02-05 12:23:04.323080

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "f5023c388e33"
down_revision: str | Sequence[str] | None = "0c83425451a8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
